services:
  - type: web
    name: oes-backend
    env: node
    rootDir: backend
    plan: free
    autoDeploy: true
    buildCommand: npm ci && npx tsc -p .
    startCommand: node dist/server.js
    envVars:
      - key: DB_ENGINE
        value: json
      - key: JWT_SECRET
        generateValue: true